# Generated by Django 4.2.5 on 2023-09-05 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(choices=[(0, 'None'), (1, 'Bachelor'), (2, 'Magister'), (3, 'Doctoral')], default=0)),
                ('contract_amount', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('otm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.otm')),
                ('student', models.ForeignKey(limit_choices_to={'is_active': True, 'is_student': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studentlar',
            },
        ),
    ]
